version: '3'
services:
  evaluation_l2d_zhang_et_al_run1:
    build:
      context: .
      dockerfile: ray_sb23_tf_torch_v2.Dockerfile
    env_file:
      - wandb_variables.env
    command: bash -c "python run_experiment.py evaluation_l2d_Zhang_et_al 'evaluation_l2d_Zhang_et_al/bench_l2d_6x6x6_cpu_4_env_rl4jsp_gen_0i_run_config.yml'"
    volumes:
      - .:/source

  evaluation_l2d_zhang_et_al_run2:
      build:
        context: .
        dockerfile: ray_sb23_tf_torch_v2.Dockerfile
      env_file:
        - wandb_variables.env
      command: bash -c "python run_experiment.py evaluation_l2d_Zhang_et_al 'evaluation_l2d_Zhang_et_al/bench_l2d_8x8x8_cpu_4_env_rl4jsp_gen_0i_run_config.yml'"
      volumes:
        - .:/source
          
  evaluation_l2d_zhang_et_al_run3:
    build:
      context: .
      dockerfile: ray_sb23_tf_torch_v2.Dockerfile
    env_file:
      - wandb_variables.env
    command: bash -c "python run_experiment.py evaluation_l2d_Zhang_et_al 'evaluation_l2d_Zhang_et_al/bench_l2d_10x10x10_cpu_4_env_rl4jsp_gen_0i_run_config.yml'"
    volumes:
      - .:/source